//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_payment
    {
        public int Id { get; set; }
        public string pay_status { get; set; }
        public string pay_supplier_name { get; set; }
        public string pay_amount { get; set; }
        public string pay_vat { get; set; }
        public string pay_vatResult { get; set; }
        public string pay_total_amount { get; set; }
        public string pay_tax { get; set; }
        public string pay_w_taxResult { get; set; }
        public string pay_total_tax { get; set; }
        public string pay_bank { get; set; }
        public string pay_createdate { get; set; }
        public string pay_timecreate { get; set; }
        public string pay_upate { get; set; }
        public string pay_timeUpdate { get; set; }
    }
}
