//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACCBILLING_NOTE.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Bank
    {
        public int Id { get; set; }
        public string BankName_EN { get; set; }
        public string Address_EN { get; set; }
        public string BankName_Thi { get; set; }
        public string Address_Thi { get; set; }
        public string AccOn { get; set; }
        public string Branch { get; set; }
        public string SwiftCode { get; set; }
    }
}
