//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_BillingHeader
    {
        public int Id { get; set; }
        public string CodeCustomer { get; set; }
        public string CustomerName { get; set; }
        public string TaxId { get; set; }
        public string Address { get; set; }
        public string Telepone { get; set; }
        public string Fax { get; set; }
        public string Date { get; set; }
        public string CreditTrem { get; set; }
        public string Bank { get; set; }
        public string FilepdfName { get; set; }
    }
}
