//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACCBILLING_NOTE.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_BillingDetail
    {
        public int Id { get; set; }
        public string OnInvoiceHeader { get; set; }
        public string OnInvoiceDetail { get; set; }
        public string Codecustomer { get; set; }
        public string Inv_date { get; set; }
        public string Inv_duedate { get; set; }
        public string Amount { get; set; }
        public string Vat { get; set; }
        public string Total { get; set; }
        public string Inv_headerDate { get; set; }
        public string CustomerName { get; set; }
        public string AccBankId { get; set; }
    }
}
