//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boi_Quotations
    {
        public int id { get; set; }
        public string itemNo { get; set; }
        public string supllierCode { get; set; }
        public string dateReceive { get; set; }
        public string quotationNo { get; set; }
        public string quotationFile { get; set; }
        public string dateEffective { get; set; }
        public string dateExpriation { get; set; }
        public string dateModify { get; set; }
        public string userCode { get; set; }
        public string quotationType { get; set; }
        public string quotationRemark { get; set; }
        public string quotationRemark1 { get; set; }
        public string quotationRemark2 { get; set; }
    }
}
