//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessPartner_Performance
    {
        public int id { get; set; }
        public string partnerId { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string dateCreate { get; set; }
        public string dateUpdate { get; set; }
        public string version { get; set; }
        public string remark { get; set; }
        public string remark1 { get; set; }
        public string userCode { get; set; }
        public string userCodeUpdate { get; set; }
    }
}
