//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpList
    {
        public int EmpID { get; set; }
        public string IDcode { get; set; }
        public string PPID { get; set; }
        public string TaxID { get; set; }
        public string SSO { get; set; }
        public string Title_TH { get; set; }
        public string FName_TH { get; set; }
        public string LName_TH { get; set; }
        public string NName_TH { get; set; }
        public string Title_EN { get; set; }
        public string FName_EN { get; set; }
        public string LName_EN { get; set; }
        public string NName_EN { get; set; }
        public string Gender { get; set; }
        public string Nation { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public Nullable<bool> Disabled_stat { get; set; }
        public string Disabled_By { get; set; }
        public string Addr_Build { get; set; }
        public string Addr_No { get; set; }
        public string Addr_Alle { get; set; }
        public string Addr_Rd { get; set; }
        public string Addr_Vill { get; set; }
        public string Addr_Prsh { get; set; }
        public string Addr_Dtrct { get; set; }
        public string Addr_Prvnc { get; set; }
        public string Addr_Post { get; set; }
        public string Educate { get; set; }
        public string In_Email { get; set; }
        public string Ex_Email { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public string Bank_Acc { get; set; }
        public string DeptCode { get; set; }
        public string DeptDesc { get; set; }
        public string Position { get; set; }
        public string CostCenter { get; set; }
        public string CostCenterName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> PassDate { get; set; }
        public Nullable<System.DateTime> StartPosition { get; set; }
        public string Note { get; set; }
        public string EmpStatus { get; set; }
        public string ReasonPPS { get; set; }
        public Nullable<System.DateTime> DatePasSport { get; set; }
        public string DatePasSportExpire { get; set; }
    }
}
