//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACCBILLING_NOTE.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeader
    {
        public int Id { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceCreateDate { get; set; }
        public System.DateTime PaymentDueDate { get; set; }
        public int MasterCustomerId { get; set; }
        public int MasterInvoiceId { get; set; }
        public string InvoiceName { get; set; }
        public string InvoiceApproverName { get; set; }
        public string InvoiceApproverPosition { get; set; }
        public string Remark { get; set; }
        public string Remark2 { get; set; }
        public Nullable<int> MasterAccHeaderForAccId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostalCode { get; set; }
        public string TelephoneNo1 { get; set; }
        public string TelephoneNo2 { get; set; }
        public string FaxNo { get; set; }
        public string Attn { get; set; }
        public int EnumRoundTypeId { get; set; }
        public int MasterCurrencyId { get; set; }
        public int EnumExchangeRateTypeId { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string PaymentTerm { get; set; }
        public Nullable<int> PaymentMonth { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal SubTotalAmount { get; set; }
        public decimal AdvanceReceiptAmount { get; set; }
        public decimal AdvanceReceiptVat { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Vat { get; set; }
        public decimal SubTotalAmountNative { get; set; }
        public decimal ExchangeRate { get; set; }
        public int MasterCurrencyNativeCurrencyId { get; set; }
        public decimal GrandTotalNative { get; set; }
        public decimal DomesticPpn { get; set; }
        public decimal GrandTotal { get; set; }
        public bool IsInvoiceIssued { get; set; }
        public Nullable<System.DateTime> InvoiceIssuedDate { get; set; }
        public bool IsInvoiceExportedToAcc { get; set; }
        public bool IsCancelled { get; set; }
        public string CancelReason { get; set; }
        public int MasterNumberingRuleId { get; set; }
        public bool IsPrinted { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public bool IsDelete { get; set; }
        public int EnumAccDocTypeId { get; set; }
        public string TaxId { get; set; }
        public string CompanyBranchName { get; set; }
        public int EnumBranchTypeId { get; set; }
        public string CustomerBranchName { get; set; }
        public string CustomerTaxId { get; set; }
        public bool IsDetailEditable { get; set; }
        public bool IsRecalculate { get; set; }
        public bool IsVoucherPrinted { get; set; }
        public Nullable<System.DateTime> VoucherPrintedDate { get; set; }
        public decimal WithholdingTax { get; set; }
        public decimal PaymentAmount { get; set; }
        public bool IsDocumentAttached { get; set; }
        public bool IsSendToCustomer { get; set; }
        public string LCNo { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string Source { get; set; }
        public string DestinationEx { get; set; }
        public string ShippingTerms { get; set; }
        public string ReferenceEx { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string ShippingMarks { get; set; }
        public string CountryOfOrigin { get; set; }
        public string Freight { get; set; }
        public int PaymentTotalCount { get; set; }
        public decimal TotalClearingBillingAmount { get; set; }
        public decimal RestBillingAmount { get; set; }
        public int EnumPaymentStatusId { get; set; }
        public Nullable<System.DateTime> BLDate { get; set; }
        public string RemarkPONo { get; set; }
        public string DONo { get; set; }
        public Nullable<int> MasterIncotermId { get; set; }
        public string CountryOfConsignee { get; set; }
        public string ShippedBy { get; set; }
        public string VesselFlightNo { get; set; }
        public Nullable<int> EnumInvoiceRemarkId { get; set; }
        public string DestinationName { get; set; }
        public string DestinationAddress1 { get; set; }
        public string DestinationAddress2 { get; set; }
        public string DestinationPostalCode { get; set; }
        public string DestinationTelephoneNo1 { get; set; }
        public string DestinationTelephoneNo2 { get; set; }
        public string DestinationFaxNo { get; set; }
        public string DestinationAttn { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterCustomer MasterCustomer { get; set; }
        public virtual MasterInvoice MasterInvoice { get; set; }
    }
}
