//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterBusinessPartner
    {
        public int Id { get; set; }
        public string BusinessPartnerCode { get; set; }
        public string BusinessPartnerName { get; set; }
        public string BusinessPartnerShortName { get; set; }
        public int EnumBusinessPartnerTypeId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostalCode { get; set; }
        public string TelephoneNo1 { get; set; }
        public string TelephoneNo2 { get; set; }
        public string FaxNo { get; set; }
        public bool IsActive { get; set; }
        public string ParentCompanyName { get; set; }
        public string ParentCompanyLocation { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
