//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterInvoice()
        {
            this.MasterCustomers = new HashSet<MasterCustomer>();
        }
    
        public int Id { get; set; }
        public string InvoiceCode { get; set; }
        public string InvoiceName { get; set; }
        public string InvoiceShortName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostalCode { get; set; }
        public string TelephoneNo1 { get; set; }
        public string TelephoneNo2 { get; set; }
        public string FaxNo { get; set; }
        public decimal PaymentTerm { get; set; }
        public string PaymentCondition { get; set; }
        public int MasterVatHeaderId { get; set; }
        public int EnumRoundTypeId { get; set; }
        public int MasterCurrencyId { get; set; }
        public int EnumExchangeRateTypeId { get; set; }
        public string TaxId { get; set; }
        public int EnumBranchTypeId { get; set; }
        public string BranchName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> MasterAccHeaderForAccId { get; set; }
        public Nullable<int> MasterInvoiceGroupId { get; set; }
        public string PersonInCharge { get; set; }
        public string EmailTo { get; set; }
        public string EmailCC1 { get; set; }
        public string EmailCC2 { get; set; }
        public string EmailCC3 { get; set; }
        public string EmailCC4 { get; set; }
        public string EmailCC5 { get; set; }
        public string EmailCC6 { get; set; }
        public string EmailCC7 { get; set; }
        public string EmailCC8 { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal OutStandingBalance { get; set; }
        public decimal AvailableCreditLimit { get; set; }
        public Nullable<int> MasterPaymentInformationId { get; set; }
        public string Attn { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterCustomer> MasterCustomers { get; set; }
    }
}
