//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACCBILLING_NOTE.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OCTIIS_WEBAPPEntities : DbContext
    {
        public OCTIIS_WEBAPPEntities()
            : base("name=OCTIIS_WEBAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acc_Bank> Acc_Bank { get; set; }
        public virtual DbSet<Acc_BillingDetail> Acc_BillingDetail { get; set; }
        public virtual DbSet<Acc_BillingHeader> Acc_BillingHeader { get; set; }
        public virtual DbSet<Acc_payment> Acc_payment { get; set; }
    }
}
