//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OCTIIS_WEBAPPEntities1 : DbContext
    {
        public OCTIIS_WEBAPPEntities1()
            : base("name=OCTIIS_WEBAPPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boi_Quotations> Boi_Quotations { get; set; }
        public virtual DbSet<Set_Permission> Set_Permission { get; set; }
        public virtual DbSet<System_Permissions> System_Permissions { get; set; }
        public virtual DbSet<BusinessPartner_Performance> BusinessPartner_Performance { get; set; }
    }
}
