//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_Permission
    {
        public int id { get; set; }
        public string userCode { get; set; }
        public string permissionId { get; set; }
        public string dateCreate { get; set; }
    }
}
