//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Permissions
    {
        public int id { get; set; }
        public string typePermission { get; set; }
        public string remarkPermission { get; set; }
        public string controllerPermission { get; set; }
        public Nullable<int> status { get; set; }
        public string remark1 { get; set; }
    }
}
