//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRight
    {
        public int USR_Id { get; set; }
        public int USE_Id { get; set; }
        public int RIH_Id { get; set; }
    
        public virtual Right Right { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
