//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOI_QUO.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.UserRights = new HashSet<UserRight>();
        }
    
        public int USE_Id { get; set; }
        public string USE_Account { get; set; }
        public string USE_Password { get; set; }
        public string USE_FName { get; set; }
        public string USE_LName { get; set; }
        public string USE_NickName { get; set; }
        public string USE_TelNo { get; set; }
        public string USE_Email { get; set; }
        public int USE_Status { get; set; }
        public string USE_Nationality { get; set; }
        public int Dep_Id { get; set; }
        public Nullable<int> USE_Usercode { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRight> UserRights { get; set; }
    }
}
